<?xml version='1.0' encoding='utf-8' standalone='yes'?>
<!DOCTYPE strongsdictionary [
   <!ELEMENT strongsdictionary (prologue, entries) >
   <!ELEMENT prologue (#PCDATA) >
   <!ELEMENT entries (entry)+ >
   <!ELEMENT entry (#PCDATA|strongs|greek|pronunciation|latin|see|strongsref)* >
   <!ATTLIST entry strongs CDATA #REQUIRED >
   <!ELEMENT greek EMPTY >
   <!ATTLIST greek BETA CDATA #REQUIRED 
                   unicode CDATA #REQUIRED >
   <!ELEMENT latin (#PCDATA) >
   <!ELEMENT pronunciation (#PCDATA) >
   <!ELEMENT strongs (#PCDATA) >
   <!ELEMENT see EMPTY >
   <!ATTLIST see language CDATA #REQUIRED
                 strongs CDATA #REQUIRED >
   <!ELEMENT strongsref EMPTY >
   <!ATTLIST strongsref language CDATA #REQUIRED
                 strongs CDATA #REQUIRED >
 ]>

<strongsdictionary><prologue>
                     Dictionary of Greek Words
			      taken from
                   Strong's Exhaustive Concordance
                                  by
                     James Strong, S.T.D., LL.D.
                                 1890

                     Public Domain -- Copy Freely

XML e-text version
==================

The XML version of this work was prepared in 2006 by Ulrik Petersen
(http://ulrikp.org) from the ASCII e-text version presented below.
The XML version contains "real" UTF-8 Greek where the original ASCII
e-text version had transliteration.  The XML has a stand-alone DTD
which should be easy to follow.

Ulrik Petersen welcomes bugfixes to the text.  Please send them to the
address provided on the website:

http://ulrikp.org


Ulrik Petersen



     -------------- original announcement follows --------------


                Dictionaries of Hebrew and Greek Words
                              taken from
                   Strong's Exhaustive Concordance
                                  by
                     James Strong, S.T.D., LL.D.
                                 1890

                     Public Domain -- Copy Freely

For a hundred years Strong's Dictionaries have been popular with Bible
students.  By assigning numbers to each unique word in the Old and New
Testaments and listing each word with its number, Strong produced a
standard, still used today, for referencing definitions. Bible
students, with little or no knowledge of Greek and Hebrew, are able to
use Strong's numbers to learn about the Greek and Hebrew of the Bible.

ASCII e-text version:
=====================

The files for this e-text were produced by Michael Grier,
mgrier@pdnt.com, in 1996, and download from
http://members.tripod.com/~SoftIdeas, in February 1998. The files have
been setup for importing into the Online Bible for DOS. But to make
these files into generic text files, all that is needed is to replace
the terms "GREEK" and "HEBREW" with "Greek" and "Hebrew" or the names
of the appropriate files.

The e-text has been changed from the printed version in three ways.

1) A five digit Strong's word number with leading zeros has been placed before
   each entry. 
2) Where Strong provides the number of another word for etymology,
   a line with "see GREEK for" or "see HEBREW for" and the number, has been
   added after Strong's entry for the word. (This is for use after
   importing into the DOS version of Online Bible, but also provides a good
   way to programmatically add links.)
3) The abbreviations used by Strong in the
   Greek dictionary, (not Hebrew) have been replaced by the abbreviated words.

Michael Grier did a check of the e-text against a printed Strong's
dictionary.  The work seems clean but more proofreading is needed to
certify it clean from errors.

Further info:
=============

If you are looking for Strong's that will self install into the Online
Bible see:
           Michael Grier
           mgrier@pdnt.com
           http://members.tripod.com/~SoftIdeas

If any errors are located, please ensure you have the latest files,
and if so, we would appreciate being informed of the error.

           Bible Foundation
           bf@bf.org
           http://www.bf.org/
           or the e-text Library
           http://www.bf.org/bfetexts.htm

</prologue><entries><entry strongs="00001">

 <strongs>1</strongs>   <greek BETA="*A" unicode="Α"/>   <pronunciation>al'-fah</pronunciation>

 of Hebrew origin; the first letter of the alphabet; figuratively, only
 (from its use as a numeral) the first: --Alpha. Often used (usually
 <greek BETA="A)/N" unicode="ἄν"/>, before a vowel) also in composition (as a contraction from <strongsref language="GREEK" strongs="427"/>) in
 the sense of privation; so, in many words, beginning with this letter;
 occasionally in the sense of union (as a contraction of <strongsref language="GREEK" strongs="260"/>).
<see language="GREEK" strongs="427"/>
<see language="GREEK" strongs="260"/>
</entry><entry strongs="00002">
 <strongs>2</strongs>   <greek BETA="*)AARW/N" unicode="Ἀαρών"/>   <pronunciation>ah-ar-ohn'</pronunciation>

 of Hebrew origin (<strongsref language="HEBREW" strongs="0175"/>); Aaron, the brother of Moses:--Aaron.
<see language="HEBREW" strongs="0175"/>
</entry><entry strongs="00003">
 <strongs>3</strongs>   <greek BETA="*)ABADDW/N" unicode="Ἀβαδδών"/>   <pronunciation>ab-ad-dohn'</pronunciation>

 of Hebrew origin (<strongsref language="HEBREW" strongs="011"/>); a destroying angel:--Abaddon.
<see language="HEBREW" strongs="011"/>
</entry><entry strongs="00004">
 <strongs>4</strongs>   <greek BETA="A)BARH/S" unicode="ἀβαρής"/>   <pronunciation>ab-ar-ace'</pronunciation>

 from <strongsref language="GREEK" strongs="1"/> (as a negative particle) and <strongsref language="GREEK" strongs="922"/>; weightless, i.e.
 (figuratively) not burdensome:--from being burdensome.
<see language="GREEK" strongs="1"/>
<see language="GREEK" strongs="922"/>
</entry><entry strongs="00005">
 <strongs>5</strongs>   <greek BETA="*)ABBA=" unicode="Ἀββᾶ"/>   <pronunciation>ab-bah'</pronunciation>

 of Chaldee origin (<strongsref language="HEBREW" strongs="02"/>); father as a vocative:--Abba.
<see language="HEBREW" strongs="02"/>
</entry><entry strongs="00006">
 <strongs>6</strongs>   <greek BETA="*)/ABEL" unicode="Ἄβελ"/>   <pronunciation>ab'-el</pronunciation>

 of Hebrew origin (<strongsref language="HEBREW" strongs="01893"/>); Abel, the son of Adam:--Abel.
<see language="HEBREW" strongs="01893"/>
</entry><entry strongs="00007">
 <strongs>7</strongs>   <greek BETA="*)ABIA/" unicode="Ἀβιά"/>   <pronunciation>ab-ee-ah'</pronunciation>

 of Hebrew origin (<strongsref language="HEBREW" strongs="029"/>); Abijah, the name of two Israelites:--Abia.
<see language="HEBREW" strongs="029"/>
</entry><entry strongs="00008">
 <strongs>8</strongs>   <greek BETA="*)ABIAQA/R" unicode="Ἀβιαθάρ"/>   <pronunciation>ab-ee-ath'-ar</pronunciation>

 of Hebrew origin (<strongsref language="HEBREW" strongs="054"/>); Abiathar, an Israelite:--Abiathar.
<see language="HEBREW" strongs="054"/>
</entry><entry strongs="00009">
 <strongs>9</strongs>   <greek BETA="*)ABILHNH/" unicode="Ἀβιληνή"/>   <pronunciation>ab-ee-lay-nay'</pronunciation>

 of foreign origin (compare <strongsref language="HEBREW" strongs="058"/>); Abilene, a region of Syria:--Abilene.
<see language="HEBREW" strongs="058"/>
</entry><entry strongs="00010">
 <strongs>10</strongs>   <greek BETA="*)ABIOU/D" unicode="Ἀβιούδ"/>   <pronunciation>ab-ee-ood'</pronunciation>

 of Hebrew origin (<strongsref language="HEBREW" strongs="031"/>); Abihud, an Israelite:--Abiud.
<see language="HEBREW" strongs="031"/>
</entry><entry strongs="00011">
 <strongs>11</strongs>   <greek BETA="*)ABRAA/M" unicode="Ἀβραάμ"/>   <pronunciation>ab-rah-am'</pronunciation>

 of Hebrew origin (<strongsref language="HEBREW" strongs="085"/>); Abraham, the Hebrew patriarch:--Abraham. (In
 Acts 7:16 the text should probably read Jacob.)
<see language="HEBREW" strongs="085"/>
</entry><entry strongs="00012">
 <strongs>12</strongs>   <greek BETA="A)/BUSSOS" unicode="ἄβυσσος"/>   <pronunciation>ab'-us-sos</pronunciation>

 from <strongsref language="GREEK" strongs="1"/> (as a negative particle) and a variation of <strongsref language="GREEK" strongs="1037"/>; depthless,
 i.e. (specially) (infernal) "abyss":--deep, (bottomless) pit.
<see language="GREEK" strongs="1"/>
<see language="GREEK" strongs="1037"/>
</entry><entry strongs="00013">
 <strongs>13</strongs>   <greek BETA="*)/AGABOS" unicode="Ἄγαβος"/>   <pronunciation>ag'-ab-os</pronunciation>

 of Hebrew origin (compare <strongsref language="HEBREW" strongs="02285"/>); Agabus, an Israelite:--Agabus.
<see language="HEBREW" strongs="02285"/>
</entry><entry strongs="00014">
 <strongs>14</strongs>   <greek BETA="A)GAQOERGE/W" unicode="ἀγαθοεργέω"/>   <pronunciation>ag-ath-er-gheh'-o</pronunciation>

 from <strongsref language="GREEK" strongs="18"/> and <strongsref language="GREEK" strongs="2041"/>; to work good:--do good.
<see language="GREEK" strongs="18"/>
<see language="GREEK" strongs="2041"/>
</entry><entry strongs="00015">
 <strongs>15</strongs>   <greek BETA="A)GAQOPOIE/W" unicode="ἀγαθοποιέω"/>   <pronunciation>ag-ath-op-oy-eh'-o</pronunciation>

 from <strongsref language="GREEK" strongs="17"/>; to be a well-doer (as a favor or a duty):--(when) do good
 (well).
<see language="GREEK" strongs="17"/>
</entry><entry strongs="00016">
 <strongs>16</strongs>   <greek BETA="A)GAQOPOII/+A" unicode="ἀγαθοποιΐα"/>   <pronunciation>ag-ath-op-oy-ee'-ah</pronunciation>

 from <strongsref language="GREEK" strongs="17"/>; well-doing, i.e. virtue:--well-doing.
<see language="GREEK" strongs="17"/>
</entry><entry strongs="00017">
 <strongs>17</strongs>   <greek BETA="A)GAQOPOIO/S" unicode="ἀγαθοποιός"/>   <pronunciation>ag-ath-op-oy-os'</pronunciation>

 from <strongsref language="GREEK" strongs="18"/> and <strongsref language="GREEK" strongs="4160"/>; a well-doer, i.e. virtuous:--them that do well.
<see language="GREEK" strongs="18"/>
<see language="GREEK" strongs="4160"/>
</entry><entry strongs="00018">
 <strongs>18</strongs>   <greek BETA="A)GAQO/S" unicode="ἀγαθός"/>   <pronunciation>ag-ath-os'</pronunciation>

 a primary word; "good" (in any sense, often as noun):--benefit,
 good(-s, things), well. Compare <strongsref language="GREEK" strongs="2570"/>.
<see language="GREEK" strongs="2570"/>
</entry><entry strongs="00019">
 <strongs>19</strongs>   <greek BETA="A)GAQWSU/NH" unicode="ἀγαθωσύνη"/>   <pronunciation>ag-ath-o-soo'-nay</pronunciation>

 from <strongsref language="GREEK" strongs="18"/>; goodness, i.e. virtue or beneficence:--goodness.
<see language="GREEK" strongs="18"/>
</entry><entry strongs="00020">
 <strongs>20</strongs>   <greek BETA="A)GALLI/ASIS" unicode="ἀγαλλίασις"/>   <pronunciation>ag-al-lee'-as-is</pronunciation>

 from <strongsref language="GREEK" strongs="21"/>; exultation; specially, welcome:--gladness, (exceeding) joy.
<see language="GREEK" strongs="21"/>
</entry><entry strongs="00021">
 <strongs>21</strongs>   <greek BETA="A)GALLIA/W" unicode="ἀγαλλιάω"/>   <pronunciation>ag-al-lee-ah'-o</pronunciation>

 from agan (much) and <strongsref language="GREEK" strongs="242"/>; properly, to jump for joy, i.e. exult:--be
 (exceeding) glad, with exceeding joy, rejoice (greatly).
<see language="GREEK" strongs="242"/>
</entry><entry strongs="00022">
 <strongs>22</strongs>   <greek BETA="A)/GAMOS" unicode="ἄγαμος"/>   <pronunciation>ag'-am-os</pronunciation>

 from <strongsref language="GREEK" strongs="1"/> (as a negative particle) and <strongsref language="GREEK" strongs="1062"/>; unmarried:--unmarried.
<see language="GREEK" strongs="1"/>
<see language="GREEK" strongs="1062"/>
</entry><entry strongs="00023">
 <strongs>23</strongs>   <greek BETA="A)GANAKTE/W" unicode="ἀγανακτέω"/>   <pronunciation>ag-an-ak-teh'-o</pronunciation>

 from <greek BETA="A)/GAN" unicode="ἄγαν"/> (much) and <greek BETA="A)/XQOS" unicode="ἄχθος"/> (grief; akin to the base of <strongsref language="GREEK" strongs="43"/>); to be
 greatly afflicted, i.e. (figuratively) indignant:--be much (sore)
 displeased, have (be moved with, with) indignation.
<see language="GREEK" strongs="43"/>
</entry><entry strongs="00024">
 <strongs>24</strongs>   <greek BETA="A)GANA/KTHSIS" unicode="ἀγανάκτησις"/>   <pronunciation>ag-an-ak'-tay-sis</pronunciation>

 from <strongsref language="GREEK" strongs="23"/>; indignation:--indignation.
<see language="GREEK" strongs="23"/>
</entry><entry strongs="00025">
 <strongs>25</strongs>   <greek BETA="A)GAPA/W" unicode="ἀγαπάω"/>   <pronunciation>ag-ap-ah'-o</pronunciation>

 perhaps from <greek BETA="A)/GAN" unicode="ἄγαν"/> (much) (or compare <strongsref language="GREEK" strongs="5689"/>); to love (in a social or
 moral sense):--(be-)love(-ed). Compare <strongsref language="GREEK" strongs="5368"/>.
<see language="GREEK" strongs="5689"/>
<see language="GREEK" strongs="5368"/>
</entry><entry strongs="00026">
 <strongs>26</strongs>   <greek BETA="A)GA/PH" unicode="ἀγάπη"/>   <pronunciation>ag-ah'-pay</pronunciation>

 from <strongsref language="GREEK" strongs="25"/>; love, i.e. affection or benevolence; specially (plural) a
 love-feast:--(feast of) charity(-ably), dear, love.
<see language="GREEK" strongs="25"/>
</entry><entry strongs="00027">
 <strongs>27</strongs>   <greek BETA="A)GAPHTO/S" unicode="ἀγαπητός"/>   <pronunciation>ag-ap-ay-tos'</pronunciation>

 from <strongsref language="GREEK" strongs="25"/>; beloved:--(dearly, well) beloved, dear.
<see language="GREEK" strongs="25"/>
</entry><entry strongs="00028">
 <strongs>28</strongs>   <greek BETA="*)/AGAR" unicode="Ἄγαρ"/>   <pronunciation>ag'-ar</pronunciation>

 of Hebrew origin (<strongsref language="HEBREW" strongs="01904"/>); Hagar, the concubine of Abraham:--Hagar.
<see language="HEBREW" strongs="01904"/>
</entry><entry strongs="00029">
 <strongs>29</strongs>   <greek BETA="A)GGAREU/W" unicode="ἀγγαρεύω"/>   <pronunciation>ang-ar-yew'-o</pronunciation>

 of foreign origin (compare <strongsref language="HEBREW" strongs="0104"/>); properly, to be a courier, i.e. (by
 implication) to press into public service:--compel (to go).
<see language="HEBREW" strongs="0104"/>
</entry><entry strongs="00030">
 <strongs>30</strongs>   <greek BETA="A)GGEI=ON" unicode="ἀγγεῖον"/>   <pronunciation>ang-eye'-on</pronunciation>

 from <greek BETA="A)/GGOS" unicode="ἄγγος"/> (a pail, perhaps as bent; compare the base of <strongsref language="GREEK" strongs="43"/>); a
 receptacle:--vessel.
<see language="GREEK" strongs="43"/>
</entry><entry strongs="00031">
 <strongs>31</strongs>   <greek BETA="A)GGELI/A" unicode="ἀγγελία"/>   <pronunciation>ang-el-ee'-ah</pronunciation>

 from <strongsref language="GREEK" strongs="32"/>; an announcement, i.e. (by implication) precept:--message.
<see language="GREEK" strongs="32"/>
</entry><entry strongs="00032">
 <strongs>32</strongs>   <greek BETA="A)/GGELOS" unicode="ἄγγελος"/>   <pronunciation>ang'-el-os</pronunciation>

 from <greek BETA="A)GGE/LLW" unicode="ἀγγέλλω"/> (probably derived from <strongsref language="GREEK" strongs="71"/>; compare <strongsref language="GREEK" strongs="34"/>) (to bring
 tidings); a messenger; especially an "angel"; by implication, a
 pastor:--angel, messenger.
<see language="GREEK" strongs="71"/>
<see language="GREEK" strongs="34"/>
</entry><entry strongs="00033">
 <strongs>33</strongs>   <greek BETA="A)/GE" unicode="ἄγε"/>   <pronunciation>ag'-eh</pronunciation>

 imperative of <strongsref language="GREEK" strongs="71"/>; properly, lead, i.e. come on:--go to.
<see language="GREEK" strongs="71"/>
</entry><entry strongs="00034">
 <strongs>34</strongs>   <greek BETA="A)GE/LH" unicode="ἀγέλη"/>   <pronunciation>ag-el'-ay</pronunciation>

 from <strongsref language="GREEK" strongs="71"/> (compare <strongsref language="GREEK" strongs="32"/>); a drove:--herd.
<see language="GREEK" strongs="71"/>
<see language="GREEK" strongs="32"/>
</entry><entry strongs="00035">
 <strongs>35</strongs>   <greek BETA="A)GENEALO/GHTOS" unicode="ἀγενεαλόγητος"/>   <pronunciation>ag-en-eh-al-og'-ay-tos</pronunciation>

 from <strongsref language="GREEK" strongs="1"/> (as negative particle) and <strongsref language="GREEK" strongs="1075"/>; unregistered as to
 birth:--without descent.
<see language="GREEK" strongs="1"/>
<see language="GREEK" strongs="1075"/>
</entry><entry strongs="00036">
 <strongs>36</strongs>   <greek BETA="A)GENH/S" unicode="ἀγενής"/>   <pronunciation>ag-en-ace'</pronunciation>

 from <strongsref language="GREEK" strongs="1"/> (as negative particle) and <strongsref language="GREEK" strongs="1085"/>; properly, without kin, i.e.
 (of unknown descent, and by implication) ignoble:--base things.
<see language="GREEK" strongs="1"/>
<see language="GREEK" strongs="1085"/>
</entry><entry strongs="00037">
 <strongs>37</strongs>   <greek BETA="A(GIA/ZW" unicode="ἁγιάζω"/>   <pronunciation>hag-ee-ad'-zo</pronunciation>

 from <strongsref language="GREEK" strongs="40"/>; to make holy, i.e. (ceremonially) purify or consecrate;
 (mentally) to venerate:--hallow, be holy, sanctify.
<see language="GREEK" strongs="40"/>
</entry><entry strongs="00038">
 <strongs>38</strongs>   <greek BETA="A(GIASMO/S" unicode="ἁγιασμός"/>   <pronunciation>hag-ee-as-mos'</pronunciation>

 from <strongsref language="GREEK" strongs="37"/>; properly, purification, i.e. (the state) purity; concretely
 (by Hebraism) a purifier:--holiness, sanctification.
<see language="GREEK" strongs="37"/>
</entry><entry strongs="00039">
 <strongs>39</strongs>   <greek BETA="A(/GION" unicode="ἅγιον"/>   <pronunciation>hag'-ee-on</pronunciation>

 neuter of <strongsref language="GREEK" strongs="40"/>; a sacred thing (i.e. spot):--holiest (of all), holy
 place, sanctuary.
<see language="GREEK" strongs="40"/>
</entry><entry strongs="00040">
 <strongs>40</strongs>   <greek BETA="A(/GIOS" unicode="ἅγιος"/>   <pronunciation>hag'-ee-os</pronunciation>

 from <greek BETA="A(/GOS" unicode="ἅγος"/> (an awful thing) (compare <strongsref language="GREEK" strongs="53"/>, <strongsref language="GREEK" strongs="2282"/>); sacred (physically,
 pure, morally blameless or religious, ceremonially,
 consecrated):--(most) holy (one, thing), saint.
<see language="GREEK" strongs="53"/>
<see language="GREEK" strongs="2282"/>
</entry><entry strongs="00041">
 <strongs>41</strongs>   <greek BETA="A(GIO/THS" unicode="ἁγιότης"/>   <pronunciation>hag-ee-ot'-ace</pronunciation>

 from <strongsref language="GREEK" strongs="40"/>; sanctity (i.e. properly, the state):--holiness.
<see language="GREEK" strongs="40"/>
</entry><entry strongs="00042">
 <strongs>42</strongs>   <greek BETA="A(GIWSU/NH" unicode="ἁγιωσύνη"/>   <pronunciation>hag-ee-o-soo'-nay</pronunciation>

 from <strongsref language="GREEK" strongs="40"/>; sacredness (i.e. properly, the quality):--holiness.
<see language="GREEK" strongs="40"/>
</entry><entry strongs="00043">
 <strongs>43</strongs>   <greek BETA="A)GKA/LH" unicode="ἀγκάλη"/>   <pronunciation>ang-kal'-ay</pronunciation>

 from <greek BETA="A)/GKOS" unicode="ἄγκος"/> (a bend, "ache"); an arm (as curved):--arm.
</entry><entry strongs="00044">
 <strongs>44</strongs>   <greek BETA="A)/GKISTRON" unicode="ἄγκιστρον"/>   <pronunciation>ang'-kis-tron</pronunciation>

 from the same as <strongsref language="GREEK" strongs="43"/>; a hook (as bent):--hook.
<see language="GREEK" strongs="43"/>
</entry><entry strongs="00045">
 <strongs>45</strongs>   <greek BETA="A)/GKURA" unicode="ἄγκυρα"/>   <pronunciation>ang'-koo-rah</pronunciation>

 from the same as <strongsref language="GREEK" strongs="43"/>; an "anchor" (as crooked):--anchor.
<see language="GREEK" strongs="43"/>
</entry><entry strongs="00046">
 <strongs>46</strongs>   <greek BETA="A)/GNAFOS" unicode="ἄγναφος"/>   <pronunciation>ag'-naf-os</pronunciation>

 from <strongsref language="GREEK" strongs="1"/> (as a negative particle) and the same as <strongsref language="GREEK" strongs="1102"/>; properly,
 unfulled, i.e. (by implication) new (cloth):--new.
<see language="GREEK" strongs="1"/>
<see language="GREEK" strongs="1102"/>
</entry><entry strongs="00047">
 <strongs>47</strongs>   <greek BETA="A(GNEI/A" unicode="ἁγνεία"/>   <pronunciation>hag-ni'-ah</pronunciation>

 from <strongsref language="GREEK" strongs="53"/>; cleanliness (the quality), i.e. (specially)
 chastity:--purity.
<see language="GREEK" strongs="53"/>
</entry><entry strongs="00048">
 <strongs>48</strongs>   <greek BETA="A(GNI/ZW" unicode="ἁγνίζω"/>   <pronunciation>hag-nid'-zo</pronunciation>

 from <strongsref language="GREEK" strongs="53"/>; to make clean, i.e. (figuratively) sanctify (ceremonially or
 morally):--purify (self).
<see language="GREEK" strongs="53"/>
</entry><entry strongs="00049">
 <strongs>49</strongs>   <greek BETA="A(GNISMO/S" unicode="ἁγνισμός"/>   <pronunciation>hag-nis-mos'</pronunciation>

 from <strongsref language="GREEK" strongs="48"/>; a cleansing (the act), i.e. (ceremonially)
 lustration:--purification.
<see language="GREEK" strongs="48"/>
</entry><entry strongs="00050">
 <strongs>50</strongs>   <greek BETA="A)GNOE/W" unicode="ἀγνοέω"/>   <pronunciation>ag-no-eh'-o</pronunciation>

 from <strongsref language="GREEK" strongs="1"/> (as a negative particle) and <strongsref language="GREEK" strongs="3539"/>; not to know (through lack of
 information or intelligence); by implication, to ignore (through
 disinclination):--(be) ignorant(-ly), not know, not understand,
 unknown.
<see language="GREEK" strongs="1"/>
<see language="GREEK" strongs="3539"/>
</entry><entry strongs="00051">
 <strongs>51</strongs>   <greek BETA="A)GNO/HMA" unicode="ἀγνόημα"/>   <pronunciation>ag-no'-ay-mah</pronunciation>

 from <strongsref language="GREEK" strongs="50"/>; a thing ignored, i.e. shortcoming:--error.
<see language="GREEK" strongs="50"/>
</entry><entry strongs="00052">
 <strongs>52</strongs>   <greek BETA="A)/GNOIA" unicode="ἄγνοια"/>   <pronunciation>ag'-noy-ah</pronunciation>

 from <strongsref language="GREEK" strongs="50"/>; ignorance (properly, the quality):--ignorance.
<see language="GREEK" strongs="50"/>
</entry><entry strongs="00053">
 <strongs>53</strongs>   <greek BETA="A(GNO/S" unicode="ἁγνός"/>   <pronunciation>hag-nos'</pronunciation>

 from the same as <strongsref language="GREEK" strongs="40"/>; properly, clean, i.e. (figuratively) innocent,
 modest, perfect:--chaste, clean, pure.
<see language="GREEK" strongs="40"/>
</entry><entry strongs="00054">
 <strongs>54</strongs>   <greek BETA="A(GNO/THS" unicode="ἁγνότης"/>   <pronunciation>hag-not'-ace</pronunciation>

 from <strongsref language="GREEK" strongs="53"/>; cleanness (the state), i.e. (figuratively)
 blamelessness:--pureness.
<see language="GREEK" strongs="53"/>
</entry><entry strongs="00055">
 <strongs>55</strongs>   <greek BETA="A(GNW=S" unicode="ἁγνῶς"/>   <pronunciation>hag-noce'</pronunciation>

 adverb from <strongsref language="GREEK" strongs="53"/>; purely, i.e. honestly:--sincerely.
<see language="GREEK" strongs="53"/>
</entry><entry strongs="00056">
 <strongs>56</strongs>   <greek BETA="A)GNWSI/A" unicode="ἀγνωσία"/>   <pronunciation>ag-no-see'-ah</pronunciation>

 from <strongsref language="GREEK" strongs="1"/> (as negative particle) and <strongsref language="GREEK" strongs="1108"/>; ignorance (properly, the
 state):--ignorance, not the knowledge.
<see language="GREEK" strongs="1"/>
<see language="GREEK" strongs="1108"/>
</entry><entry strongs="00057">
 <strongs>57</strongs>   <greek BETA="A)/GNWSTOS" unicode="ἄγνωστος"/>   <pronunciation>ag'-noce-tos'</pronunciation>

 from <strongsref language="GREEK" strongs="1"/> (as negative particle) and <strongsref language="GREEK" strongs="1110"/>; unknown:--unknown.
<see language="GREEK" strongs="1"/>
<see language="GREEK" strongs="1110"/>
</entry><entry strongs="00058">
 <strongs>58</strongs>   <greek BETA="A)GORA/" unicode="ἀγορά"/>   <pronunciation>ag-or-ah'</pronunciation>

 from <greek BETA="A)GEI/RW" unicode="ἀγείρω"/> (to gather; probably akin to <strongsref language="GREEK" strongs="1453"/>); properly, the
 town-square (as a place of public resort); by implication, a market or
 thoroughfare:--market(-place), street.
<see language="GREEK" strongs="1453"/>
</entry><entry strongs="00059">
 <strongs>59</strongs>   <greek BETA="A)GORA/ZW" unicode="ἀγοράζω"/>   <pronunciation>ag-or-ad'-zo</pronunciation>

 from <strongsref language="GREEK" strongs="58"/>; properly, to go to market, i.e. (by implication) to purchase;
 specially, to redeem:--buy, redeem.
<see language="GREEK" strongs="58"/>
</entry><entry strongs="00060">
 <strongs>60</strongs>   <greek BETA="A)GORAI=OS" unicode="ἀγοραῖος"/>   <pronunciation>ag-or-ah'-yos</pronunciation>

 from <strongsref language="GREEK" strongs="58"/>; relating to the market-place, i.e. forensic (times); by
 implication, vulgar:--baser sort, low.
<see language="GREEK" strongs="58"/>
</entry><entry strongs="00061">
 <strongs>61</strongs>   <greek BETA="A)/GRA" unicode="ἄγρα"/>   <pronunciation>ag'-rah</pronunciation>

 from <strongsref language="GREEK" strongs="71"/>; (abstractly) a catching (of fish); also (concretely) a haul
 (of fish):--draught.
<see language="GREEK" strongs="71"/>
</entry><entry strongs="00062">
 <strongs>62</strongs>   <greek BETA="A)GRA/MMATOS" unicode="ἀγράμματος"/>   <pronunciation>ag-ram-mat-os</pronunciation>

 from <strongsref language="GREEK" strongs="1"/> (as negative particle) and <strongsref language="GREEK" strongs="1121"/>; unlettered, i.e.
 illiterate:--unlearned.
<see language="GREEK" strongs="1"/>
<see language="GREEK" strongs="1121"/>
</entry><entry strongs="00063">
 <strongs>63</strongs>   <greek BETA="A)GRAULE/W" unicode="ἀγραυλέω"/>   <pronunciation>ag-row-leh'-o</pronunciation>

 from <strongsref language="GREEK" strongs="68"/> and <strongsref language="GREEK" strongs="832"/> (in the sense of <strongsref language="GREEK" strongs="833"/>); to camp out:--abide in the
 field.
<see language="GREEK" strongs="68"/>
<see language="GREEK" strongs="832"/>
<see language="GREEK" strongs="833"/>
</entry><entry strongs="00064">
 <strongs>64</strongs>   <greek BETA="A)GREU/W" unicode="ἀγρεύω"/>   <pronunciation>ag-rew'-o</pronunciation>

 from <strongsref language="GREEK" strongs="61"/>; to hunt, i.e. (figuratively) to entrap:--catch.
<see language="GREEK" strongs="61"/>
</entry><entry strongs="00065">
 <strongs>65</strongs>   <greek BETA="A)GRIE/LAIOS" unicode="ἀγριέλαιος"/>   <pronunciation>ag-ree-el'-ah-yos</pronunciation>

 from <strongsref language="GREEK" strongs="66"/> and <strongsref language="GREEK" strongs="1636"/>; an oleaster:--olive tree (which is) wild.
<see language="GREEK" strongs="66"/>
<see language="GREEK" strongs="1636"/>
</entry><entry strongs="00066">
 <strongs>66</strongs>   <greek BETA="A)/GRIOS" unicode="ἄγριος"/>   <pronunciation>ag'-ree-os</pronunciation>

 from <strongsref language="GREEK" strongs="68"/>; wild (as pertaining to the country), literally (natural) or
 figuratively (fierce):--wild, raging.
<see language="GREEK" strongs="68"/>
</entry><entry strongs="00067">
 <strongs>67</strongs>   <greek BETA="*)AGRI/PPAS" unicode="Ἀγρίππας"/>   <pronunciation>ag-rip'-pas</pronunciation>

 apparently from <strongsref language="GREEK" strongs="66"/> and <strongsref language="GREEK" strongs="2462"/>; wild-horse tamer; Agrippas, one of the
 Herods:--Agrippa.
<see language="GREEK" strongs="66"/>
<see language="GREEK" strongs="2462"/>
</entry><entry strongs="00068">
 <strongs>68</strongs>   <greek BETA="A)GRO/S" unicode="ἀγρός"/>   <pronunciation>ag-ros'</pronunciation>

 from <strongsref language="GREEK" strongs="71"/>; a field (as a drive for cattle); genitive case, the country;
 specially, a farm, i.e. hamlet:--country, farm, piece of ground, land.
<see language="GREEK" strongs="71"/>
</entry><entry strongs="00069">
 <strongs>69</strongs>   <greek BETA="A)GRUPNE/W" unicode="ἀγρυπνέω"/>   <pronunciation>ag-roop-neh'-o</pronunciation>

 ultimately from <strongsref language="GREEK" strongs="1"/> (as negative particle) and <strongsref language="GREEK" strongs="5258"/>; to be sleepless,
 i.e. keep awake:--watch.
<see language="GREEK" strongs="1"/>
<see language="GREEK" strongs="5258"/>
</entry><entry strongs="00070">
 <strongs>70</strongs>   <greek BETA="A)GRUPNI/A" unicode="ἀγρυπνία"/>   <pronunciation>ag-roop-nee'-ah</pronunciation>

 from <strongsref language="GREEK" strongs="69"/>; sleeplessness, i.e. a keeping awake:--watch.
<see language="GREEK" strongs="69"/>
</entry><entry strongs="00071">
 <strongs>71</strongs>   <greek BETA="A)/GW" unicode="ἄγω"/>   <pronunciation>ag'-o</pronunciation>

 a primary verb; properly, to lead; by implication, to bring, drive,
 (reflexively) go, (specially) pass (time), or (figuratively)
 induce:--be, bring (forth), carry, (let) go, keep, lead away, be open.
</entry><entry strongs="00072">
 <strongs>72</strongs>   <greek BETA="A)GWGH/" unicode="ἀγωγή"/>   <pronunciation>ag-o-gay'</pronunciation>

 reduplicated from <strongsref language="GREEK" strongs="71"/>; a bringing up, i.e. mode of living:--manner of
 life.
<see language="GREEK" strongs="71"/>
</entry><entry strongs="00073">
 <strongs>73</strongs>   <greek BETA="A)GW/N" unicode="ἀγών"/>   <pronunciation>ag-one'</pronunciation>

 from <strongsref language="GREEK" strongs="71"/>; properly, a place of assembly (as if led), i.e. (by
 implication) a contest (held there); figuratively, an effort or
 anxiety:--conflict, contention, fight, race.
<see language="GREEK" strongs="71"/>
</entry><entry strongs="00074">
 <strongs>74</strongs>   <greek BETA="A)GWNI/A" unicode="ἀγωνία"/>   <pronunciation>ag-o-nee'-ah</pronunciation>

 from <strongsref language="GREEK" strongs="73"/>; a struggle (properly, the state), i.e. (figuratively)
 anguish:--agony.
<see language="GREEK" strongs="73"/>
</entry><entry strongs="00075">
 <strongs>75</strongs>   <greek BETA="A)GWNI/ZOMAI" unicode="ἀγωνίζομαι"/>   <pronunciation>ag-o-nid'-zom-ahee</pronunciation>

 from <strongsref language="GREEK" strongs="73"/>; to struggle, literally (to compete for a prize), figuratively